import { useCallback, useState } from "react";
import { Badge, Button, Tooltip, useApiKey } from "../ui";
import type { Finding } from "../lib/check";
import type { MessageStructure } from "../lib/structure";
import { describeAiError, explainFinding, type Explanation } from "../lib/ai";

/* ========================================================================== *
 * The one place the workbench talks to a model.
 *
 * It is attached to a finding the deterministic checker has ALREADY made, and it says —
 * before anything is sent — exactly what leaves the browser. Nothing here can change a
 * verdict: if the request fails, the finding is unaffected and the error is shown verbatim.
 * ========================================================================== */

export interface AiExplainProps {
  finding: Finding;
  structure: MessageStructure;
  /** A few lines of the message around the finding, for context. */
  snippet?: string;
}

export function AiExplain({ finding, structure, snippet }: AiExplainProps) {
  const { key } = useApiKey();
  const [state, setState] = useState<{
    loading: boolean;
    error: string | null;
    result: Explanation | null;
  }>({ loading: false, error: null, result: null });

  const run = useCallback(async () => {
    setState({ loading: true, error: null, result: null });
    try {
      const result = await explainFinding(key, finding, structure, snippet);
      setState({ loading: false, error: null, result });
    } catch (err) {
      setState({ loading: false, error: describeAiError(err), result: null });
    }
  }, [key, finding, structure, snippet]);

  if (!key) {
    return (
      <Tooltip
        wide
        content="Set an Anthropic API key in the header to have a model turn this finding into a HIS-side fix. The structural verdict above does not use it."
      >
        <span className="cursor-help font-mono text-2xs text-ink-3">
          AI explanation needs a key
        </span>
      </Tooltip>
    );
  }

  if (state.result) {
    const r = state.result;
    return (
      <div className="rounded-sm border border-line bg-inset p-2 text-xs">
        <div className="mb-1 flex items-center gap-1.5">
          <Badge tone="accent" mono>
            AI
          </Badge>
          <Badge tone={r.confidence === "high" ? "ok" : r.confidence === "medium" ? "warn" : "error"}>
            {r.confidence} confidence
          </Badge>
          <button
            type="button"
            onClick={() => setState({ loading: false, error: null, result: null })}
            className="ml-auto font-mono text-2xs text-ink-3 hover:text-ink"
          >
            dismiss
          </button>
        </div>
        <p className="text-ink">{r.plainLanguage}</p>
        <p className="mt-1 text-ink-2">
          <span className="text-2xs uppercase tracking-wide text-ink-3">Usually caused by: </span>
          {r.hisSideCause}
        </p>
        <p className="mt-1 text-ink-2">
          <span className="text-2xs uppercase tracking-wide text-ink-3">Fix: </span>
          {r.fix}
        </p>
        {r.unresolved.length ? (
          <ul className="mt-1 list-disc pl-4 text-2xs text-warn">
            {r.unresolved.map((u, i) => (
              <li key={i}>{u}</li>
            ))}
          </ul>
        ) : null}
        <p className="mt-1.5 text-2xs text-ink-3">
          Generated by a model from the finding above. The structural verdict itself came from
          the compiled specification, not from this.
        </p>
      </div>
    );
  }

  return (
    <div className="flex items-center gap-1.5">
      <Button size="xs" onClick={run} disabled={state.loading}>
        {state.loading ? "Asking…" : "Explain for my HIS team"}
      </Button>
      <span className="text-2xs text-ink-3">
        sends this finding{snippet ? " and the lines around it" : ""} to Anthropic
      </span>
      {state.error ? <span className="text-2xs text-error">{state.error}</span> : null}
    </div>
  );
}
